"""add_file_key_to_pqs

Revision ID: 86da761ad5e6
Revises: 789c10705a3e
Create Date: 2026-09-02 13:31:47.107312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86da761ad5e6'
down_revision: Union[str, Sequence[str], None] = '789c10705a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqs', sa.Column('file_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('pqs_uploader_id_fkey'), 'pqs', type_='foreignkey')
    op.create_foreign_key(None, 'pqs', 'users', ['uploader_id'], ['id'])
    op.drop_constraint(op.f('programme_courses_course_id_fkey'), 'programme_courses', type_='foreignkey')
    op.drop_constraint(op.f('programme_courses_programme_id_fkey'), 'programme_courses', type_='foreignkey')
    op.create_foreign_key(None, 'programme_courses', 'programmes', ['programme_id'], ['id'])
    op.create_foreign_key(None, 'programme_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(op.f('users_programme_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'programmes', ['programme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_programme_id_fkey'), 'users', 'programmes', ['programme_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'programme_courses', type_='foreignkey')
    op.drop_constraint(None, 'programme_courses', type_='foreignkey')
    op.create_foreign_key(op.f('programme_courses_programme_id_fkey'), 'programme_courses', 'programmes', ['programme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('programme_courses_course_id_fkey'), 'programme_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pqs', type_='foreignkey')
    op.create_foreign_key(op.f('pqs_uploader_id_fkey'), 'pqs', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pqs', 'file_name')
    # ### end Alembic commands ###
