"""add college column

Revision ID: dc74deaf02d6
Revises: 3ff872e0932d
Create Date: 2026-08-09 05:42:30.195473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc74deaf02d6'
down_revision: Union[str, Sequence[str], None] = '3ff872e0932d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'college')
    # ### end Alembic commands ###
