"""add user_id

Revision ID: a2b3cff4f327
Revises: 1a53100cd21d
Create Date: 2026-07-24 11:30:01.337508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b3cff4f327'
down_revision: Union[str, Sequence[str], None] = '1a53100cd21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pqs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pqs', type_='foreignkey')
    op.drop_column('pqs', 'user_id')
    # ### end Alembic commands ###
