"""fix foreignkey relationships btw programme-user and uploader-pq

Revision ID: b1aa33cef98d
Revises: 4858047877d2
Create Date: 2026-08-14 14:43:09.053158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1aa33cef98d'
down_revision: Union[str, Sequence[str], None] = '4858047877d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqs', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('pqs_user_id_fkey'), 'pqs', type_='foreignkey')
    op.create_foreign_key(None, 'pqs', 'users', ['uploader_id'], ['id'])
    op.drop_column('pqs', 'user_id')
    op.add_column('users', sa.Column('programme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'programmes', ['programme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'programme_id')
    op.add_column('pqs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pqs', type_='foreignkey')
    op.create_foreign_key(op.f('pqs_user_id_fkey'), 'pqs', 'users', ['user_id'], ['id'])
    op.drop_column('pqs', 'uploader_id')
    # ### end Alembic commands ###
